### ISSUE TITLE
Circular dependecy between Test::META and URI

### ISSUE THREAD

**Issue by frithnanth** [raku-community-modules/URI#46]
In the URI module there's a test, t/001-meta.t in which I see these lines:
```raku
BEGIN {
    require Test::META <&meta-ok>;
```
while the Test::META module lists URI as a dependency in its META6.json:
```json
"depends": [
    "Test",
    "META6",
    "URI",
    "License::SPDX"
  ],
```
Right now the only way to install those modules is to `zef install --/test` one of them.

**Comment by jonathanstowe** [comment]
In the first instance I'll see if I can lose the dependency on URI in Test::META (I think it's there to test for a valid source url,)  otherwise we'll need to lose the test.

**Comment by jonathanstowe** [comment]
I think I'll lose the META test in URI as validating that there is a good source URI in Test::META is fairly key :-D

**Comment by jonathanstowe** [comment]
Cheers!
